export const MELI_QUERY_ENDPOINT = process.env.MELI_QUERY_ENDPOINT;
export const MELI_ITEM_DETAILS_ENDPOINT =
  process.env.MELI_ITEM_DETAILS_ENDPOINT;
export const MELI_ITEM_DESCRIPTION_ENDPOINT =
  process.env.MELI_ITEM_DESCRIPTION_ENDPOINT;
export const ITEMS_ENDPOINT = process.env.ITEMS_ENDPOINT;
export const ITEM_DETAILS_ENDPOINT = process.env.ITEM_DETAILS_ENDPOINT;
export const MAX_RESULTS_COUNT = process.env.MAX_RESULTS_COUNT;
